# Generated by Django 4.0.6 on 2023-02-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='was_ongoing',
            field=models.BooleanField(default=False),
        ),
    ]
