# Generated by Django 4.0.6 on 2023-02-17 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_test_was_ongoing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='ban_detail',
        ),
    ]
